/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PaymentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "recordPayment"
      | "recordSubscriptionPayment"
      | "registerOrder"
      | "registerSubscription"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OrderCreated"
      | "PaymentCompleted"
      | "SubscriptionCreated"
      | "SubscriptionPayment"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "recordPayment",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordSubscriptionPayment",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerOrder",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSubscription",
    values: [string, AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "recordPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSubscriptionPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSubscription",
    data: BytesLike
  ): Result;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: string,
    merchant: AddressLike,
    amount: BigNumberish,
    currency: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    merchant: string,
    amount: bigint,
    currency: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: string;
    merchant: string;
    amount: bigint;
    currency: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCompletedEvent {
  export type InputTuple = [
    orderId: string,
    customer: AddressLike,
    amount: BigNumberish,
    memo: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    customer: string,
    amount: bigint,
    memo: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: string;
    customer: string;
    amount: bigint;
    memo: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCreatedEvent {
  export type InputTuple = [
    subscriptionId: string,
    merchant: AddressLike,
    customer: AddressLike,
    amount: BigNumberish,
    interval: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: string,
    merchant: string,
    customer: string,
    amount: bigint,
    interval: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    subscriptionId: string;
    merchant: string;
    customer: string;
    amount: bigint;
    interval: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionPaymentEvent {
  export type InputTuple = [
    subscriptionId: string,
    customer: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: string,
    customer: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    subscriptionId: string;
    customer: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentRegistry;
  waitForDeployment(): Promise<this>;

  interface: PaymentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  recordPayment: TypedContractMethod<
    [orderId: string, memo: string, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordSubscriptionPayment: TypedContractMethod<
    [subscriptionId: string, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerOrder: TypedContractMethod<
    [orderId: string, amount: BigNumberish, currency: string],
    [void],
    "nonpayable"
  >;

  registerSubscription: TypedContractMethod<
    [
      subscriptionId: string,
      customer: AddressLike,
      amount: BigNumberish,
      interval: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "recordPayment"
  ): TypedContractMethod<
    [orderId: string, memo: string, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordSubscriptionPayment"
  ): TypedContractMethod<
    [subscriptionId: string, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerOrder"
  ): TypedContractMethod<
    [orderId: string, amount: BigNumberish, currency: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerSubscription"
  ): TypedContractMethod<
    [
      subscriptionId: string,
      customer: AddressLike,
      amount: BigNumberish,
      interval: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCompleted"
  ): TypedContractEvent<
    PaymentCompletedEvent.InputTuple,
    PaymentCompletedEvent.OutputTuple,
    PaymentCompletedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCreated"
  ): TypedContractEvent<
    SubscriptionCreatedEvent.InputTuple,
    SubscriptionCreatedEvent.OutputTuple,
    SubscriptionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionPayment"
  ): TypedContractEvent<
    SubscriptionPaymentEvent.InputTuple,
    SubscriptionPaymentEvent.OutputTuple,
    SubscriptionPaymentEvent.OutputObject
  >;

  filters: {
    "OrderCreated(string,address,uint256,string,uint256)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "PaymentCompleted(string,address,uint256,string,uint256)": TypedContractEvent<
      PaymentCompletedEvent.InputTuple,
      PaymentCompletedEvent.OutputTuple,
      PaymentCompletedEvent.OutputObject
    >;
    PaymentCompleted: TypedContractEvent<
      PaymentCompletedEvent.InputTuple,
      PaymentCompletedEvent.OutputTuple,
      PaymentCompletedEvent.OutputObject
    >;

    "SubscriptionCreated(string,address,address,uint256,uint256,uint256)": TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;
    SubscriptionCreated: TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;

    "SubscriptionPayment(string,address,uint256,uint256)": TypedContractEvent<
      SubscriptionPaymentEvent.InputTuple,
      SubscriptionPaymentEvent.OutputTuple,
      SubscriptionPaymentEvent.OutputObject
    >;
    SubscriptionPayment: TypedContractEvent<
      SubscriptionPaymentEvent.InputTuple,
      SubscriptionPaymentEvent.OutputTuple,
      SubscriptionPaymentEvent.OutputObject
    >;
  };
}
